nav:
  - Home: index.md
  - Modding Tools:
    - Empire at War Tools:
      - tools/eaw/map_editor.md
      - tools/eaw/particle_editor.md
      - tools/eaw/alo_viewer.md
    - Code Editors:
      - tools/code/vscode.md
    - Modelling Tools:
      - tools/modelling/blender.md
      - tools/modelling/autodesk.md
    - Texturing Tools:
      - tools/texturing/substance_suite.md
  - Technical Documentation:
    - Lua:
      - techdoc/lua/eaw-lua-tips.md
      - techdoc/lua/foc-lua-scripts.md
      - techdoc/lua/luafunctions.md
      - Scripts:
        - Libraries:
          - techdoc/lua/libraries/pgdebug.md
          - techdoc/lua/libraries/pgbase.md
          - techdoc/lua/libraries/pgbasedefinitions.md
          - techdoc/lua/libraries/pgcommands.md
          - techdoc/lua/libraries/pgaicommands.md
          - techdoc/lua/libraries/pgstatemachine.md
          - techdoc/lua/libraries/pgmoveunits.md
          - techdoc/lua/libraries/pgspawnunits.md
          - techdoc/lua/libraries/pgstorymode.md
    - Xml:
      - techdoc/xml/xml-tag-overview.md
      - techdoc/xml/xml-events-rewards.md
######################### DO NOT EDIT BELOW THIS LINE #########################
  - Tags: tags.md
site_name: Star Wars: Empire at War - Unofficial Modding Documentation
site_url: https://aet-sweaw-modding.readthedocs.io
repo_url: https://github.com/AlamoEngine-Tools/eaw-doc-pages
repo_name: 'GitHub'
edit_uri: edit/main/docs/
site_description: The community maintained documentation for Star Wars - Empire at War and Star Wars - Empire at War - Forces of Corruption
site_author: Alamo Engine Tools and contributors
copyright: Copyright &copy; Alamo Engine Tools and contributors. All rights reserved. Licensed under the MIT license. See LICENSE file in the project root for details.
theme:
  name: material
  custom_dir: docs/overrides
  palette:
    primary: indigo
  logo: assets/aet_icon.png
  favicon: assets/aet_icon.png
  font: false # [gruenwaldlk]: Disable google fonts for GDPR compliance. TODO: Add new (EaW specific) fonts.
  features:
#    - navigation.tabs
    - navigation.expand
    - navigation.instant    
    - navigation.tracking
#    - navigation.indexes # [gruenwaldlk]: Disabled, insiders only.
markdown_extensions:
  - toc:
      permalink: true
  - codehilite:
      linenums: true
  - admonition
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - smarty
plugins:
    - search:
        lang: en
    - git-authors
    - git-revision-date-localized:
        fallback_to_build_date: true
        type: timeago
        timezone: Europe/Amsterdam
        exclude:
          - tags.md
    - tags:
        tags_folder: /tmp/mysite/tgs
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/AlamoEngine-Tools/eaw-doc-pages
    - icon: fontawesome/brands/discord
      link: https://discord.gg/QCaDEdKkVP
