nav:
  - Home: index.md
  - Modding Tools:
    - Empire at War Tools:
      - tools/eaw/map_editor.md
      - tools/eaw/particle_editor.md
      - tools/eaw/alo_viewer.md
    - Code Editors:
      - tools/code/vscode.md
    - Modelling Tools:
      - tools/modelling/blender.md
      - tools/modelling/autodesk.md
    - Texturing Tools:
      - tools/texturing/substance_suite.md
  - Technical Documentation:
    #- Game Systems:
    #  - Data:
    #  - Story Scripting:
    #  - AI:
    - Known Issues and Quirks:
      - LUA:
        - techdoc/issues/lua/issues.md
    - References:
      - LUA:
        - techdoc/reference/lua/eaw-lua-tips.md
        - techdoc/reference/lua/foc-lua-scripts.md
        - techdoc/reference/lua/luafunctions.md
        - Libraries:
          - techdoc/reference/lua/libraries/pgdebug.md
          - techdoc/reference/lua/libraries/pgbase.md
          - techdoc/reference/lua/libraries/pgbasedefinitions.md
          - techdoc/reference/lua/libraries/pgcommands.md
          - techdoc/reference/lua/libraries/pgaicommands.md
          - techdoc/reference/lua/libraries/pgstatemachine.md
          - techdoc/reference/lua/libraries/pgmoveunits.md
          - techdoc/reference/lua/libraries/pgspawnunits.md
          - techdoc/reference/lua/libraries/pgstorymode.md
      - Xml:
        - techdoc/reference/xml/xml-tag-overview.md
        - techdoc/reference/xml/xml-events-rewards.md
######################### DO NOT EDIT BELOW THIS LINE #########################
site_name: Star Wars - Empire at War - Unofficial Modding Documentation
site_url: https://aet-sweaw-modding.readthedocs.io
repo_url: https://github.com/AlamoEngine-Tools/eaw-doc-pages
repo_name: 'GitHub'
edit_uri: edit/main/docs/
site_description: The community maintained documentation for Star Wars - Empire at War and Star Wars - Empire at War - Forces of Corruption
site_author: Alamo Engine Tools and contributors
copyright: Copyright &copy; Alamo Engine Tools and contributors. All rights reserved. Licensed under the MIT license. See LICENSE file in the project root for details.
theme:
  name: material
  custom_dir: docs/overrides
  palette:
    primary: indigo
  logo: assets/aet_icon.png
  favicon: assets/aet_icon.png
  font: false # [gruenwaldlk]: Disable google fonts for GDPR compliance. TODO: Add new (EaW specific) fonts.
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.instant    
    - navigation.tracking
    - navigation.path
    - navigation.sections
    - navigation.top
    - toc.follow
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
markdown_extensions:
  - toc:
      permalink: true
  - codehilite:
      linenums: true
  - admonition
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - smarty
plugins:
    - search:
        lang: en
    - git-authors
    - git-revision-date-localized:
        fallback_to_build_date: true
        type: timeago
        timezone: Europe/Amsterdam
    - tags:
        tags_folder: /tmp/mysite/tgs
        tags_file: index.md
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/AlamoEngine-Tools/eaw-doc-pages
