site_name: EaW ModHub Documentation
site_url: https://eaw-mod-hub-documentation.readthedocs.io
repo_url: https://github.com/AlamoEngine-Tools/eaw-doc-pages
repo_name: 'GitHub'
edit_uri: edit/main/docs/
site_description: The community maintained EaW Mod Hub Documentation for Star Wars - Empire at War and Star Wars - Empire at War - Forces of Corruption
site_author: Alamo Engine Tools and contributors
copyright: Copyright (c) 2021 Alamo Engine Tools and contributors. All rights reserved. Licensed under the MIT license. See LICENSE file in the project root for details.

theme:
  name: readthedocs
  custom_dir: docs/overrides

markdown_extensions:
  - toc:
      permalink: true
  - codehilite:
      linenums: true
  - smarty

nav:
  - Home: index.md
  - Modding Tools:
    - Empire at War Tools:
      - tools/eaw/map_editor.md
      - tools/eaw/particle_editor.md
      - tools/eaw/alo_viewer.md
    - Code Editors:
      - tools/code/vscode.md
    - Modelling Tools:
      - tools/modelling/blender.md
      - tools/modelling/autodesk.md
    - Texturing Tools:
      - tools/texturing/substance_suite.md
  - Tags: tags.md

plugins:
    - search 
    - git-authors
    - git-revision-date-localized:
        fallback_to_build_date: true
        type: timeago
        timezone: Europe/Amsterdam
        exclude:
          - tags.md
    - tags:
        tags_folder: /tmp/mysite/tgs
